### ISSUE TITLE
Does this support DTLS?

### ISSUE THREAD

**Issue by itsnikolayy** [wolfSSL/go-wolfssl#10]
I was unable to find any references to DTLS in this repo, but just in case, does go-wolfssl support DTLS or not?

**Comment by lealem47** [comment]
Hi @itsnikolayy,

DTLS is not currently supported but it wouldn't be hard to add. I can spend some time on it in the coming week to get it supported.

In the meanwhile, can you tell us a little bit about your project?

Thanks,
Lealem @ wolfSSL

**Comment by lealem47** [comment]
Hi @itsnikolayy,

I've put up the PR for adding in DTLS support in https://github.com/wolfSSL/go-wolfssl/pull/11. I will work on getting it merged soon.

It would still be nice to hear about what you're working on.
