### ISSUE TITLE
Could not determine kind of name for C.WC_SHA512_DIGEST_SIZE

### ISSUE THREAD

**Issue by cody0704** [wolfSSL/go-wolfssl#5]
* go version: go1.20.1 linux/amd64
* os: Ubuntu 20.04 LTS

## Install Wolfssl

```bash
git clone https://github.com/wolfSSL/wolfssl
./autogen.sh
./configure
make
sudo make install
```

## Build Failed

I followed the instructions for installation, but encountered the following issue.

<img width="1360" alt="圖片" src="https://github.com/wolfSSL/go-wolfssl/assets/57340378/059c762e-21d4-4053-81b7-3b84ce4e38fd">

**Comment by anhu** [comment]
Hi @cody0704, 
Thank you for your interest in wolfSSL!!  
From your message above, I noticed that you did not mention any calls like this: 

```
go get -u github.com/wolfssl/go-wolfssl 
```

Such a step is documented in the README.md file here: 

https://github.com/wolfSSL/go-wolfssl/blob/master/README.md

Please let me know if this helps.
Can you please let us know more about your project and what you are trying to accomplish? 

Warm regards, Anthony

**Comment by cody0704** [comment]
Hi @anhu ,

Thank you for your response. 

I apologize for not documenting the complete installation process I followed. 
Rest assured, I did proceed according to the steps outlined in 'https://github.com/wolfSSL/go-wolfssl/blob/master/README.md'. 

This included executing the following command:

```bash
go get -u github.com/wolfssl/go-wolfssl 
```

I am conducting an experiment where I aim to perform SSL offloading using the Intel QAT Card 8970 in conjunction with wolfssl and intel qat. This is due to the lack of hardware offloading capabilities in crypto/tls.

Best Regards,
Cody

**Comment by cody0704** [comment]
Hi @anhu ,

I've managed to resolve the issue. Considering the creation date of the repository is Jun 16, 2022, I chose to install wolfSSL v5.3.0 (May 4, 2022). After doing so, the problem was solved. I'm unsure about the latest version of wolfSSL supported by go-wolfssl. 

However, I believe it may be necessary to amend the README to the following:

```bash
git clone https://github.com/wolfSSL/wolfssl
cd wolfssl
git checkout v5.3.0-stable
./autogen.sh
./configure
make
sudo make install
```

Thanks,
Cody

**Comment by anhu** [comment]
Hi Cody, I see from your output that you were successful.  This is great news. 

> I am conducting an experiment where I aim to perform SSL offloading using the Intel QAT Card 8970 in conjunction with wolfssl and intel qat. 

Very interesting!!  May I ask, is this a personal, academic or professional experiment? 

Warm regards, Anthony

**Comment by anhu** [comment]
Cody? Can you let me know a bit about your project?

**Comment by cody0704** [comment]
> Cody? Can you let me know a bit about your project?

I just came back from a vacation, I apologize for responding to you only now.
This is a professional experiment.

The aim is to carry out TLS Offload using wolfSSL + Intel QAT.
As previously mentioned, golang's crypto/tls does not support HW Offload.
Furthermore, cryptographic operations are extremely resource-intensive, which can lead to overall poorer performance.
We will attempt to use this on the DNS over TLS service.
Previously, ssl termination was done through Nginx before passing it into golang.
I want to try using go-wolfSSL directly to see if it can provide better performance.
If this approach is successful, wolfSSL would be a great choice.

I'm still setting up some aspects of the environment, which will take a bit of time. If there are any results, I would be very happy to share them.

**Comment by anhu** [comment]
Hi Cody, 
That's really interesting! Thank you very much for the information. 
Warm regards, Anthony

**Comment by anhu** [comment]
> If this solution is successful, I would be more than happy to share it...

That would be most excellent!  I'd love to know how it goes.  You can send your results to anthony@wolfssl.com .  Please do keep me updated with your progress. 

Now that you have found success, I will proceed to close this ticket. 

Warm regards, Anthony
