### ISSUE TITLE
Post-Quantum Certificates support in go-wolfssl

### ISSUE THREAD

**Issue by NomanNasirMinhas** [wolfSSL/go-wolfssl#9]
Is there a way to use falcon/dilithium etc certificates with different security levels with go-wolfssl?

**Comment by anhu** [comment]
Hi @NomanNasirMinhas , 

My name is Anthony and I am a member of the wolfSSL team. 

Yes!! Simply generate the certificates and make sure they work as specified in the wolfSSL `INSTALL` file.  You can then use those certificates with go-wolfssl.  You shouldn't need to make any code changes in your application. 

Warm regards, Anthony

**Comment by NomanNasirMinhas** [comment]
Thank you for your response @anhu . I am currently on Mac M1 but when building wolfssl as mentioned in the `INSTALL` file but I am getting following error when I run . `./server -v 4 --pqc P521_KYBER_LEVEL5` 
```
dyld[61016]: Library not loaded: @rpath/liboqs.4.dylib
  Referenced from: <515CCDE3-26FB-35FD-83C4-E841BAF36CCC> /wolfssl/examples/server/.libs/server
  Reason: tried: '/wolfssl/src/.libs/liboqs.4.dylib' (no such file)
zsh: abort      ./server -v 4 --pqc P521_KYBER_LEVEL5
```

**Comment by anhu** [comment]
Hello @NomanNasirMinhas , 

I believe on Mac, you need to set the `DYLD_LIBRARY_PATH` to point to the location of the liboqs dynamic library. 

Warm regards, Anthony

**Comment by anhu** [comment]
Interesting. Its looking in /wolfssl/src/.libs/ which is where your build of wolfssl.??.dylib would be.  This is because the actual executable is at .libs/server and ./server is script that redefines DYLD_LIBRARY_PATH.  At least that's how it works on Linux. 

Try this: 
```
DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:../src/.libs/  ./.libs/server  -v 4 --pqc P521_KYBER_LEVEL5
```

**Comment by NomanNasirMinhas** [comment]
![Screenshot 2023-12-07 at 2 35 45 PM](https://github.com/wolfSSL/go-wolfssl/assets/28532113/da44669b-6953-4fa8-9518-b44b07e41715)

**Comment by NomanNasirMinhas** [comment]
Also, I tried running the go-wolfssl on Ubuntu WSL on Windows 10. I am getting below error. Although wolfssl is working but, go-wolfssl is failing with the shown error
![image](https://github.com/wolfSSL/go-wolfssl/assets/28532113/46109e60-6553-4762-be48-eb8fe73473bf)

**Comment by anhu** [comment]
By the way, you were originally asking about signature schemes.  Kyber is a KEM for key exchange.  

Warm regards, Anthony

**Comment by NomanNasirMinhas** [comment]
> That is unexpected. Can you let me know what parameters were on your `configure` command line?

![image](https://github.com/wolfSSL/go-wolfssl/assets/28532113/e73acba8-2ac4-4681-8bc3-e2220b91b49e)

**Comment by NomanNasirMinhas** [comment]
Which KEM and DigSig can be used with go-wolfssl? Can you list them please
